# Generated by Django 4.2.30 on 2026-05-27 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='seminars/banners/')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location_url', models.URLField(blank=True, help_text='Link meeting online')),
                ('is_online', models.BooleanField(default=True)),
                ('max_participants', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminars', to='seminars.category')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('early_bird', 'Early Bird')], default='regular', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quota', models.PositiveIntegerField(default=50)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='seminars.seminar')),
            ],
            options={
                'unique_together': {('seminar', 'ticket_type')},
            },
        ),
    ]
