# Generated by Django 4.2.30 on 2026-05-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='location_url',
            field=models.CharField(blank=True, help_text='Link meeting online atau alamat lokasi', max_length=500),
        ),
    ]
